Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HandItDown.Data;
using HandItDown.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace HandItDown.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
      
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public BooksController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)

        {
            _userManager = userManager;
            _context = context;
        }

        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        // GET: Books
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();

            var applicationDbContext = _context.Book
                .Include(b => b.User)
                .Include(b => b.Status)
                .Where(t => t.UserId == user.Id);

            return View(await applicationDbContext.ToListAsync());

        }
            // GET: Books/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Status)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        { 

            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "Label");
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BookId,Title,Author,Quantity,UserId,StatusId")] Book book)
        {
            ModelState.Remove("User");
            ModelState.Remove("UserId");


            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                book.User = user;
                book.UserId = user.Id;

                _context.Add(book);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "Label", book.StatusId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", book.UserId);
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "Label", book.StatusId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", book.UserId);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BookId,Title,Author,Quantity,UserId,StatusId")] Book book)
        {
            if (id != book.BookId)
            {
                return NotFound();
            }

            ModelState.Remove("UserId");
            ModelState.Remove("User");

            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                book.User = user;
                book.UserId = user.Id;

                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.BookId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "Label", book.StatusId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", book.UserId);
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Status)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.BookId == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            _context.Book.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(int id)
        {
            return _context.Book.Any(e => e.BookId == id);
        }
    }
}

Controllers/ToysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HandItDown.Data;
using HandItDown.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace HandItDown.Controllers
{
    [Authorize]
    public class ToysController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        public ToysController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }
        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);


        // GET: Toys
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var applicationDbContext = _context.Toy
                .Include(t => t.User)
                .Include(t => t.ToyType)
                .Include(t => t.Status)
                .Where(t => t.UserId == user.Id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Toys/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toy = await _context.Toy
                .Include(t => t.Status)
                .Include(t => t.ToyType)
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.ToyId == id);
            if (toy == null)
            {
                return NotFound();
            }

            return View(toy);
        }

        // GET: Toys/Create
        public IActionResult Create()
        {
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "Label");
            ViewData["ToyTypeId"] = new SelectList(_context.ToyType, "ToyTypeId", "Label");
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Toys/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ToyId,Description,Quantity,Color,UserId,ImagePath,StatusId,ToyTypeId")] Toy toy)
        {
            ModelState.Remove("User");
            ModelState.Remove("UserId");

            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
                toy.User = user;
                toy.UserId = user.Id;

                _context.Add(toy);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "Label", toy.StatusId);
            ViewData["ToyTypeId"] = new SelectList(_context.ToyType, "ToyTypeId", "Label", toy.ToyTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", toy.UserId);
            return View(toy);
        }

        // GET: Toys/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toy = await _context.Toy.FindAsync(id);
            if (toy == null)
            {
                return NotFound();
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "Label", toy.StatusId);
            ViewData["ToyTypeId"] = new SelectList(_context.ToyType, "ToyTypeId", "Label", toy.ToyTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", toy.UserId);
            return View(toy);
        }

        // POST: Toys/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ToyId,Description,Quantity,Color,UserId,ImagePath,StatusId,ToyTypeId")] Toy toy)
        {
            if (id != toy.ToyId)
            {
                return NotFound();
            }
            ModelState.Remove("UserId");
            ModelState.Remove("User");

            if (ModelState.IsValid)
            {

                var user = await GetCurrentUserAsync();
                toy.User = user;
                toy.UserId = user.Id;

                try
                {
                    _context.Update(toy);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ToyExists(toy.ToyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["StatusId"] = new SelectList(_context.Statuses, "StatusId", "Label", toy.StatusId);
            ViewData["ToyTypeId"] = new SelectList(_context.ToyType, "ToyTypeId", "Label", toy.ToyTypeId);
            ViewData["UserId"] = new SelectList(_context.ApplicationUsers, "Id", "Id", toy.UserId);
            return View(toy);
        }

        // GET: Toys/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var toy = await _context.Toy
                .Include(t => t.Status)
                .Include(t => t.ToyType)
                .Include(t => t.User)
                .FirstOrDefaultAsync(m => m.ToyId == id);
            if (toy == null)
            {
                return NotFound();
            }

            return View(toy);
        }

        // POST: Toys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var toy = await _context.Toy.FindAsync(id);
            _context.Toy.Remove(toy);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ToyExists(int id)
        {
            return _context.Toy.Any(e => e.ToyId == id);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>This application is used by parents to keep track of their childrens items. But ultimately to also have the option 
    to move certain items to a donation list that other family members can find and elect to claim items from. 
    In addition a list of items can be created as a wish list allowing other family members to match up items they
    may be donating. The ultimate purpose is to prevent waste and duplication by providing an exchange platform for
    families.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    <strong>Support:</strong> <a href="mailto:klausheina@gmail.com">klausheina@gmail.com</a><br />
</address>

Views/Home/DonatingList.cshtml
@model HandItDown.Models.HomeViewModels.HomeIndexViewModel

@{
    ViewData["Title"] = "Donating";
}

<h2>Donating</h2>


<table class="table">
    <thead>

        <tr>
            <th>
                Donating Items:
            </th>
            <th>

            </th>
        </tr>

    </thead>


    <tbody>
        @foreach (var item in Model.Books)
        {
            <tr>
                <td>
                    <a asp-controller="Books" asp-action="Details" asp-route-id="@item.BookId">@Html.DisplayFor(modelItem => item.Title)</a>
                </td>

            </tr>
        }



        @foreach (var item in Model.Toys)
        {
            <tr>
                <td>
                    <a asp-controller="Toys" asp-action="Details" asp-route-id="@item.ToyId">@Html.DisplayFor(modelItem => item.Description)</a>
                </td>


            </tr>
        }

        @foreach (var item in Model.Clothings)
        {
            <tr>
                <td>
                    <a asp-controller="Clothings" asp-action="Details" asp-route-id="@item.ClothingId">@Html.DisplayFor(modelItem => item.Description)</a>
                </td>

            </tr>
        }


        @foreach (var item in Model.Miscs)
        {
            <tr>
                <td>
                    <a asp-controller="Miscs" asp-action="Details" asp-route-id="@item.MiscId">@Html.DisplayFor(modelItem => item.Description)</a>
                </td>


            </tr>
        }



    </tbody>
</table>

Views/Home/Index.cshtml
@model HandItDown.Models.HomeViewModels.HomeIndexViewModel;

@{
    ViewData["Title"] = "Home Page";
}



<div>
    <h1>Welcome to Toy Tracker </h1>
    <h3>An application to keep track of your child's items, create a wish list and show items to donate for family and friends.</h3>
</div>

Views/Home/Search.cshtml
@model HandItDown.Models.HomeViewModels.HomeIndexViewModel

@{
    ViewData["Title"] = "Search";
}

<h2>Search Results</h2>


<table class="table">
    <thead>
           
        <tr>
            <th>
                Search Results:
            </th>
            <th>
               
            </th>
        </tr>

    </thead>


    <tbody>
        @foreach (var item in Model.Books)
        {
            <tr>
                <td>
                    <a asp-controller="Books" asp-action="Details" asp-route-id="@item.BookId">@Html.DisplayFor(modelItem => item.Title)</a>
                </td>

            </tr>
        }



            @foreach (var item in Model.Toys)
            {
                <tr>
                    <td>
                        <a asp-controller="Toys" asp-action="Details" asp-route-id="@item.ToyId">@Html.DisplayFor(modelItem => item.Description)</a>
                    </td>

  
                </tr>
            }

            @foreach (var item in Model.Clothings)
            {
                <tr>
                    <td>
                        <a asp-controller="Clothings" asp-action="Details" asp-route-id="@item.ClothingId">@Html.DisplayFor(modelItem => item.Description)</a>
                    </td>
                    
                </tr>
            }


            @foreach (var item in Model.Miscs)
            {
                <tr>
                    <td>
                        <a asp-controller="Miscs" asp-action="Details" asp-route-id="@item.MiscId">@Html.DisplayFor(modelItem => item.Description)</a>
                    </td>

                   
                </tr>
            }


    
    </tbody>
</table>

Views/Home/WishList.cshtml
@model HandItDown.Models.HomeViewModels.HomeIndexViewModel

@{
    ViewData["Title"] = "Search";
}

<h2>Wish List</h2>


<table class="table">
    <thead>

        <tr>
            <th>
                Wish List Items:
            </th>
            <th>

            </th>
        </tr>

    </thead>


    <tbody>
        @foreach (var item in Model.Books)
        {
            <tr>
                <td>
                    <a asp-controller="Books" asp-action="Details" asp-route-id="@item.BookId">@Html.DisplayFor(modelItem => item.Title)</a>
                </td>

            </tr>
        }



        @foreach (var item in Model.Toys)
        {
            <tr>
                <td>
                    <a asp-controller="Toys" asp-action="Details" asp-route-id="@item.ToyId">@Html.DisplayFor(modelItem => item.Description)</a>
                </td>


            </tr>
        }

        @foreach (var item in Model.Clothings)
        {
            <tr>
                <td>
                    <a asp-controller="Clothings" asp-action="Details" asp-route-id="@item.ClothingId">@Html.DisplayFor(modelItem => item.Description)</a>
                </td>

            </tr>
        }


        @foreach (var item in Model.Miscs)
        {
            <tr>
                <td>
                    <a asp-controller="Miscs" asp-action="Details" asp-route-id="@item.MiscId">@Html.DisplayFor(modelItem => item.Description)</a>
                </td>


            </tr>
        }



    </tbody>
</table>